---
- name: make ansible run a script
  hosts: localhost

  tasks:
  - script: /home/student/mycode/ansible/pyhello2.py
    args:
      executable: python3
      creates: /home/student/stopper.txt
    register: results

  - debug:
      var: results
